project/apps/urls.py
from django.urls import path
from . import views

app_name = 'apps'

urlpatterns = [
    path('likes', views.likes, name='likes'),
    path('like_click', views.like_click, name='like_click'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('apps/', include('apps.urls')),
]

project/apps/models.py
from django.db import models

# Create your models here.
class Love(models.Model):
    isLike = (
        (0, 'dislike'),
        (1, 'like'),
    )
    like = models.IntegerField(default=0, choices=isLike)

project/apps/views.py
from django.shortcuts import render
from .models import Love
from django.http import JsonResponse
# Create your views here.
def likes(request):
    Love.objects.get_or_create(pk=1)
    return render(request, 'apps/clickDBevent.html')

def like_click(request):
    islike = Love.objects.get_or_create(pk=1)
    if islike[0].like:#like cancle
        like_value = islike[0].like = 0
        islike[0].save()
        return JsonResponse({'like_value':like_value})
    else:#like
        like_value = islike[0].like = 1
        islike[0].save()
        return JsonResponse({'like_value':like_value})

project/apps/templates/apps/clickDBevent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ClickDBEvent</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <style>
        #heart{
            font-size:10rem;
            color:#dc3545;
        }
    </style>
</head>
<body>
    <div>
        <i id="heart" class="far fa-heart" data-id="heart-1"></i>
    </div>
    <script>
        // 비동기통신 작성필요
        let heartClick = document.getElementById('heart')
        function request(method, url){
            return new Promise(function(res, rej){
                let xhr = new XMLHttpRequest();
                xhr.open(method, url);
                xhr.onload = res;
                xhr.onerror = rej;
                xhr.send();
            });
        }
        heartClick.addEventListener('click', e => {
            request('GET', "{% url 'apps:like_click' %}")
                .then(function(e){
                    console.log(e.target.response);
                    let data = JSON.parse(e.target.response)
                    console.log(data.like_value)
                    if(data.like_value){
                        heartClick.classList.remove('far')
                        heartClick.classList.add('fas')
                    }else{
                        heartClick.classList.remove('fas')
                        heartClick.classList.add('far')
                    }
                }, function(error){
                    // handle errors
                    console.log(error)
            });
        })
    </script>
</body>
</html>

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>JS</title>
</head>
<body>
    {% block base %}
    {% endblock %}
</body>
</html>